### ISSUE TITLE
Layout básico da página inicial 

### ISSUE THREAD

**Issue by KelvinyHenrique** [ukecode/web-page#1]
![Home](https://user-images.githubusercontent.com/21090726/79028052-09875980-7b65-11ea-9e10-af15bbcc5dbb.png)

### A fazer

- [x] Background 
- [x] Barra de navegação
- [x] Logo
- [x] Textos 
- [x] Botões
- [x] Ícones de redes sociais
- [x] Ícone do foguete para ancorar no menu inicial
- [x] Vetores de fundo
- [x] Responsividade 

**Cores**
Background: `#3388D3`
Button: `#F68E1E`

**Textos**

> Codando o Futuro

> Código, Música, Amizades? Acha que isso tem a ver com você? A UkeCode nasceu exatamente por causa disso. Somos amigos que decidiram fazer projetos juntos. Conheça mais da nossa história e venha "codar" conosco...`

**ASSETS**

[Vetores](https://www.dropbox.com/sh/5khpdx0lz7duhp5/AAC8DxMgyX-LPeu7ElXynLVsa?dl=0)

**Comment by KelvinyHenrique** [comment]
Qualquer comentário

**Comment by caio-emidio** [comment]
@KelvinyHenrique Serio? Achei q era um comentario qualquer
