### ISSUE TITLE
Página Sobre

### ISSUE THREAD

**Issue by KelvinyHenrique** [ukecode/web-page#2]
![image](https://user-images.githubusercontent.com/21090726/79028577-e362b900-7b66-11ea-906c-1653cbe071ed.png)

- [x] Titulo
- [x] Imagem
- [x] Texto
- [x] Layout responsivo

**Textos**

`Font-Family: Montserrat`
> Sobre nós
> A UkeCode nasceu em 2019 da ideia de trabalharmos em comunidade. Em um papo descontraido , Caio Carnelós conversou com Henrique Todos os membros iniciais se conheceram a partir de comunidades online e decidiram juntos construirem projetos visando qualidade e conhecimento. Gostou? Junte-se a nós em um proximo projeto

### Assets

[Vetores](https://www.dropbox.com/sh/rhjhlvt1ta8ynv2/AADbx1w1ZBWHIlg7qOf_lw9ga?dl=0)

**Comment by pyviking** [comment]
Conclusão da página sobre.
Preciso que façam a análise para mim antes de aprovar.
