### ISSUE TITLE
Nosso Time

### ISSUE THREAD

**Issue by KelvinyHenrique** [ukecode/web-page#3]
![image](https://user-images.githubusercontent.com/21090726/79029297-296d4c00-7b6a-11ea-9cd3-75cf5ddb54a8.png)

### Tarefas

- [x] Título
- [x] Box para imagem
- [x] Nome
- [x]  Imagem
- [ ] Slider
- [ ] Slider Buttons
- [x] Layout responsivo

### Font

> Font-Family: Montserrat

### Cores
Background: `#EBEDED`
Slider-Buttons: `#3388D3`

### Assets

> [Vetores](https://www.dropbox.com/sh/cq1rw0jb5ogtzpg/AACRgsTAEx7hlYcscKhLaZm2a?dl=0)

**Comment by caio-emidio** [comment]
Somente para lembrar que:

https://leprechaum-nestjs-dev.herokuapp.com/web/members
ja entrega os nomes/fotos .

Nao devera ter alteracoes no futuro :)

**Comment by caio-emidio** [comment]
Nao devera ter alteracoes no futuro da estrutura entregue
# O site devera mudar logo
## de:
leprechaum-nestjs-dev.herokuapp.com
## para:
leprechaum-nestjs.herokuapp.com
