### ISSUE TITLE
Timeline

### ISSUE THREAD

**Issue by KelvinyHenrique** [ukecode/web-page#4]
![image](https://user-images.githubusercontent.com/21090726/79029826-866a0180-7b6c-11ea-9a00-4eeabd913b34.png)

### A fazer

- [x] Título
- [x] Linha
- [x] Box conteúdo
- [x]  Círculos
- [x] Ícones dos círculos
- [x] Layout responsivo

### Cores

- `#11699B`
- `#FFC500`  
- `#DF2D3D`
- `#930A64`
- `#1C9DBC`
- `#F79530`
- `#D7006B`
- `#11699B`
- `#01D5A3`

**Comment by caio-emidio** [comment]
Para o middleware(Backend): 
A issue eh essa aqui.
https://github.com/ukecode/ms-middleware-leprechaum/issues/37
