### ISSUE TITLE
Projetos

### ISSUE THREAD

**Issue by KelvinyHenrique** [ukecode/web-page#5]
![image](https://user-images.githubusercontent.com/21090726/79030351-f9747780-7b6e-11ea-9f29-f922a0af003a.png)

### A fazer 

- [ ] Título 
- [ ] Box projeto
- [ ] Slider Buttons
- [ ] Slider
- [ ] Layout responsivo

### Cores

Backgound: `#3388D3`;

**Comment by caio-emidio** [comment]
Somente para lembrar que:

https://leprechaum-nestjs-dev.herokuapp.com/web/projects
ja entrega os nomes/fotos/url(github)
de 2 projetos

Nao devera ter alteracoes no futuro da estrutura entregue
# O site devera mudar logo
## de:
leprechaum-nestjs-dev.herokuapp.com
## para:
leprechaum-nestjs.herokuapp.com

**Comment by KelvinyHenrique** [comment]
@caio-emidio  De onde está saindo a foto dos projetos?
