### ISSUE TITLE
Statistics 

### ISSUE THREAD

**Issue by KelvinyHenrique** [ukecode/web-page#6]
![image](https://user-images.githubusercontent.com/21090726/79030504-a7802180-7b6f-11ea-8e2e-45c4ac5526cc.png)

### A fazer 

- [x] Add icons
- [x] Alinhar itens
- [x] Layout responsivo

### Cores

> Background: `#EDEBEB`

### Assets

> [Vetores](https://www.dropbox.com/sh/ryrjqati7gk3u1z/AABI5QiP_jcBKLoF82oycgx1a?dl=0)

**Comment by caio-emidio** [comment]
Podemos ate colocar um valor imaginario aqui de zoeira.
mas a duvida eh... como vamos pegar esses valores? 
Git api faz isso?

**Comment by KelvinyHenrique** [comment]
@caio-emidio https://line-count.herokuapp.com/ukecode/web-page
